version: '2.2'

volumes:
    redis_data: {}
    mongo_data: {}
    mongo_conf: {}
    data: {}

services:
    web:
        restart: always
        image: cemulate/sharelatex-full:v2.1.1
        depends_on:
            mongo:
                condition: service_healthy
            redis:
                condition: service_started
        privileged: true
        ports:
            - 80:80
        links:
            - mongo
            - redis
        volumes:
            - data:/var/lib/sharelatex
            - /var/run/docker.sock:/var/run/docker.sock
        environment:
            SHARELATEX_APP_NAME: Overleaf Community Edition
            SHARELATEX_MONGO_URL: mongodb://mongo/sharelatex
            SHARELATEX_REDIS_HOST: redis
            REDIS_HOST: redis
            ENABLED_LINKED_FILE_TYPES: 'url,project_file'
            ENABLE_CONVERSIONS: 'true'

    mongo:
        restart: always
        image: mongo:4
        container_name: mongo
        expose:
            - 27017
        volumes:
            - mongo_data:/data/db
            - mongo_conf:/data/configdb
        healthcheck:
            test: echo 'db.stats().ok' | mongo localhost:27017/test --quiet
            interval: 10s
            timeout: 10s
            retries: 5

    redis:
        restart: always
        image: redis:5-alpine
        container_name: redis
        expose:
            - 6379
        volumes:
            - redis_data:/data

